# Generated by Django 4.2.7 on 2023-11-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payment", "0001_initial"),
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="property.booking"
            ),
        ),
    ]
