# Generated by Django 4.2.7 on 2023-11-21 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0002_alter_property_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="property",
            unique_together={("owner", "name")},
        ),
    ]
